full code review

diff --git a/alpine-base/rootfs/usr/local/bin/ecol b/alpine-base/rootfs/usr/local/bin/ecol
--- a/alpine-base/rootfs/usr/local/bin/ecol
+++ b/alpine-base/rootfs/usr/local/bin/ecol
@@ -1,11 +1,14 @@
 #!/bin/sh
 
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  ecol
-#%   DESCRIPTION:  Get the nth column from the given string
-#%   USAGE: ecol [-d , ] 2[:8] "$(psp salt)" OR psp salt | ecol [-d ,] 2[:8]
-#%   REQUIRES: cut, tr, awk, estrip, printf
+#   NAME:  ecol
+#   DESCRIPTION:  Get the nth column from the given string
+#   USAGE: ecol [-d , ] 2[:8] "$(psp salt)" OR psp salt | ecol [-d ,] 2[:8]
+#   REQUIRES: cut, tr, awk, estrip, printf
 #----------------------------------------------------------------------------------------------------------------------
 _ecol() {
     local dlm=" "
diff --git a/alpine-base/rootfs/usr/local/bin/erow b/alpine-base/rootfs/usr/local/bin/erow
--- a/alpine-base/rootfs/usr/local/bin/erow
+++ b/alpine-base/rootfs/usr/local/bin/erow
@@ -1,11 +1,14 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  erow
-#%   DESCRIPTION:  Get the nth row from the given string
-#%   USAGE: erow 2[:6] "$(psp salt)" OR psp salt | erow 2[:6]
-#%   REQUIRES: cut, awk
+#   NAME:  erow
+#   DESCRIPTION:  Get the nth row from the given string
+#   USAGE: erow 2[:6] "$(psp salt)" OR psp salt | erow 2[:6]
+#   REQUIRES: cut, awk
 #----------------------------------------------------------------------------------------------------------------------
 _erow() {
     if echo "$1" | grep -q : 2>/dev/null; then
diff --git a/alpine-base/rootfs/usr/local/bin/escape b/alpine-base/rootfs/usr/local/bin/escape
--- a/alpine-base/rootfs/usr/local/bin/escape
+++ b/alpine-base/rootfs/usr/local/bin/escape
@@ -1,11 +1,14 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  escape
-#%   DESCRIPTION:  Escape special chars of the given string.
-#%   USAGE: escape "the string" or "$(escape "the string")"
-#%   REQUIRES: sed
+#   NAME:  escape
+#   DESCRIPTION:  Escape special chars of the given string.
+#   USAGE: escape "the string" or "$(escape "the string")"
+#   REQUIRES: sed
 #----------------------------------------------------------------------------------------------------------------------
 _escape() {
     if [ $# -lt 1 ]; then
@@ -41,9 +44,7 @@ _escape() {
    fi
 }
 
-
 _escape "$@"
-
 
 unset -f _escape
 exit 0
diff --git a/alpine-base/rootfs/usr/local/bin/escapes b/alpine-base/rootfs/usr/local/bin/escapes
--- a/alpine-base/rootfs/usr/local/bin/escapes
+++ b/alpine-base/rootfs/usr/local/bin/escapes
@@ -1,9 +1,14 @@
 #!/bin/sh
 
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
 
-#%   DESCRIPTION:  Escape special chars of the given string.
-#%   USAGE: escapes "the string" or "$(escapes "the string")" or echo "the string" | escapes
-#%   REQUIRES: escape
+
+#---  FUNCTION  -------------------------------------------------------------------------------------------------------
+#   DESCRIPTION:  Escape special chars of the given string.
+#   USAGE: escapes "the string" or "$(escapes "the string")" or echo "the string" | escapes
+#   REQUIRES: escape
+#----------------------------------------------------------------------------------------------------------------------
 
 if [ $# -lt 1 ]; then
     escape "$(cat)"
diff --git a/alpine-base/rootfs/usr/local/bin/estrip b/alpine-base/rootfs/usr/local/bin/estrip
--- a/alpine-base/rootfs/usr/local/bin/estrip
+++ b/alpine-base/rootfs/usr/local/bin/estrip
@@ -1,12 +1,14 @@
 #!/bin/sh
-    
 
-## require shbin/escape
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
+
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  estrip [estrip -em "$(cat /etc/apt/sources.list)" OR cat /etc/apt/sources.list | estrip -cm | estrip -e]
-#%   DESCRIPTION:  Strip special chars from the given string.
-#%   USAGE: estrip [-a|-an|-b|-ct|-cm|-cl|-d|-e|-em|-f|-h|-lo|-m|-ml|-n|-p|-q|-r|-rl|-sp|-u|-ub|-up] "string"
-#%   REQUIRES: escape, tr, sed, awk
+#   NAME:  estrip [estrip -em "$(cat /etc/apt/sources.list)" OR cat /etc/apt/sources.list | estrip -cm | estrip -e]
+#   DESCRIPTION:  Strip special chars from the given string.
+#   USAGE: estrip [-a|-an|-b|-ct|-cm|-cl|-d|-e|-em|-f|-h|-lo|-m|-ml|-n|-p|-q|-r|-rl|-sp|-u|-ub|-up] "string"
+#   REQUIRES: escape, tr, sed, awk
 #----------------------------------------------------------------------------------------------------------------------
 _estrip() {
     case "$1" in
@@ -257,7 +259,6 @@ _estrip() {
     esac
     return 0
 }
-
 
 _estrip "$@"
 
diff --git a/alpine-base/rootfs/usr/local/bin/estrips b/alpine-base/rootfs/usr/local/bin/estrips
--- a/alpine-base/rootfs/usr/local/bin/estrips
+++ b/alpine-base/rootfs/usr/local/bin/estrips
@@ -1,10 +1,15 @@
 #!/bin/sh
-    
 
-#%   DESCRIPTION:  Strip special chars from the given string.
-#%   USAGE: echo "string" | estrips [-a|-an|-b|-ct|-cm|-cl|-d|-e|-em|-f|-h|-lo|-m|-ml|-n|-p|-q|-r|-rl|-sp|-u|-ub|-up]
-#%          estrips [-a|-an|-b|-ct|-cm|-cl|-d|-e|-em|-f|-h|-lo|-m|-ml|-n|-p|-q|-r|-rl|-sp|-u|-ub|-up] "string"
-#%   REQUIRES: estrip
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
+
+#---  FUNCTION  -------------------------------------------------------------------------------------------------------
+#   DESCRIPTION:  Strip special chars from the given string.
+#   USAGE: echo "string" | estrips [-a|-an|-b|-ct|-cm|-cl|-d|-e|-em|-f|-h|-lo|-m|-ml|-n|-p|-q|-r|-rl|-sp|-u|-ub|-up]
+#          estrips [-a|-an|-b|-ct|-cm|-cl|-d|-e|-em|-f|-h|-lo|-m|-ml|-n|-p|-q|-r|-rl|-sp|-u|-ub|-up] "string"
+#   REQUIRES: estrip
+#----------------------------------------------------------------------------------------------------------------------
 
 if [ $# -lt 1 ]; then
     estrip "$(cat)"
diff --git a/alpine-base/rootfs/usr/local/bin/getpid b/alpine-base/rootfs/usr/local/bin/getpid
--- a/alpine-base/rootfs/usr/local/bin/getpid
+++ b/alpine-base/rootfs/usr/local/bin/getpid
@@ -1,13 +1,16 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  getpid
-#%   DESCRIPTION:  Get the first pid by exactly matching the given process name, path etc
-#%   USAGE: getpid [nth] process_name | process_path
-#%   REQUIRES: tr, erow, getpidsbyglob
+#   NAME:  getpid
+#   DESCRIPTION:  Get the first pid by exactly matching the given process name, path etc
+#   USAGE: getpid [nth] process_name | process_path
+#   REQUIRES: tr, erow, getpidsbyglob
 #----------------------------------------------------------------------------------------------------------------------
-_getpid() {
+_get_pid() {
     if [ $# -lt 1 ]; then
         echo "Usage: getpid [nth] [process_name | process_path]" >&2
         return 1
@@ -30,7 +33,7 @@ _getpid() {
 
 }
 
-_getpid "$@"
+_get_pid "$@"
 
-unset -f _getpid
+unset -f _get_pid
 exit 0
diff --git a/alpine-base/rootfs/usr/local/bin/getpidsbyglob b/alpine-base/rootfs/usr/local/bin/getpidsbyglob
--- a/alpine-base/rootfs/usr/local/bin/getpidsbyglob
+++ b/alpine-base/rootfs/usr/local/bin/getpidsbyglob
@@ -1,13 +1,16 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  getpidsbyglob
-#%   DESCRIPTION:  Get the pids list by glob matching the given name, path etc
-#%   USAGE: getpidsbyglob process_name | process_path
-#%   REQUIRES: pgrep, ps, grep, awk
+#   NAME:  getpidsbyglob
+#   DESCRIPTION:  Get the pids list by glob matching the given name, path etc
+#   USAGE: getpidsbyglob process_name | process_path
+#   REQUIRES: pgrep, ps, grep, awk
 #----------------------------------------------------------------------------------------------------------------------
-_getpidsbyglob() {
+_get_pids_by_glob() {
     if [ $# -ne 1 ]; then
         echo "Usage: getpidsbyglob process_name | process_path" >&2
         return 1
@@ -26,7 +29,7 @@ _getpidsbyglob() {
     fi
 }
 
-_getpidsbyglob "$@"
+_get_pids_by_glob "$@"
 
-unset -f _getpidsbyglob
+unset -f _get_pids_by_glob
 exit 0
diff --git a/alpine-base/rootfs/usr/local/bin/getpidsbyname b/alpine-base/rootfs/usr/local/bin/getpidsbyname
--- a/alpine-base/rootfs/usr/local/bin/getpidsbyname
+++ b/alpine-base/rootfs/usr/local/bin/getpidsbyname
@@ -1,13 +1,16 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  getpidsbyname
-#%   DESCRIPTION:  Get the exact pid of a given process name
-#%   USAGE: getpidsbyname salt-master
-#%   REQUIRES: pidof, pgrep, ps, grep, awk
+#   NAME:  getpidsbyname
+#   DESCRIPTION:  Get the exact pid of a given process name
+#   USAGE: getpidsbyname salt-master
+#   REQUIRES: pidof, pgrep, ps, grep, awk
 #----------------------------------------------------------------------------------------------------------------------
-_getpidsbyname() {
+_get_pids_by_name() {
     if [ $# -ne 1 ]; then
         echo "Usage: getpidsbyname process_name" >&2
         return 1
@@ -29,7 +32,7 @@ _getpidsbyname() {
     fi
 }
 
-_getpidsbyname "$@"
+_get_pids_by_name "$@"
 
-unset -f _getpidsbyname
+unset -f _get_pids_by_name
 exit 0
diff --git a/alpine-base/rootfs/usr/local/bin/getpnamebyid b/alpine-base/rootfs/usr/local/bin/getpnamebyid
--- a/alpine-base/rootfs/usr/local/bin/getpnamebyid
+++ b/alpine-base/rootfs/usr/local/bin/getpnamebyid
@@ -1,13 +1,16 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  getpname
-#%   DESCRIPTION:  Get the process name of the given pid
-#%   USAGE: getpnamebyid process_id | process_path
-#%   REQUIRES: tr, ps
+#   NAME:  getpnamebyid
+#   DESCRIPTION:  Get the process name of the given pid
+#   USAGE: getpnamebyid process_id | process_path
+#   REQUIRES: tr, ps
 #----------------------------------------------------------------------------------------------------------------------
-_getpname() {
+_get_pname_by_id() {
     if [ $# -ne 1 ]; then
         echo "Usage: getpnamebyid process_id | process_path" >&2
         return 1
@@ -28,7 +31,7 @@ _getpname() {
 }
 
 
-_getpname "$@"
+_get_pname_by_id "$@"
 
-unset -f _getpname
+unset -f _get_pname_by_id
 exit 0
diff --git a/alpine-base/rootfs/usr/local/bin/getppath b/alpine-base/rootfs/usr/local/bin/getppath
--- a/alpine-base/rootfs/usr/local/bin/getppath
+++ b/alpine-base/rootfs/usr/local/bin/getppath
@@ -1,13 +1,16 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  getppath
-#%   DESCRIPTION:  Get the process path of the given pid
-#%   USAGE: getppath process_id | process_name
-#%   REQUIRES: tr, getpnamebyid, getpidsbyname, head, ps ,grep, abspath
+#   NAME:  getppath
+#   DESCRIPTION:  Get the process path of the given pid
+#   USAGE: getppath process_id | process_name
+#   REQUIRES: tr, getpnamebyid, getpidsbyname, head, ps ,grep, abspath
 #----------------------------------------------------------------------------------------------------------------------
-_getppath() {
+_get_ppath() {
     if [ $# -ne 1 ]; then
         echo "Usage: getppath process_id | process_name" >&2
         return 1
@@ -43,8 +46,7 @@ _getppath() {
     fi
 }
 
+_get_ppath "$@"
 
-_getppath "$@"
-
-unset -f _getppath
+unset -f _get_ppath
 exit 0
diff --git a/alpine-base/rootfs/usr/local/bin/isdigit b/alpine-base/rootfs/usr/local/bin/isdigit
--- a/alpine-base/rootfs/usr/local/bin/isdigit
+++ b/alpine-base/rootfs/usr/local/bin/isdigit
@@ -1,11 +1,14 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  isdigit
-#%   DESCRIPTION:  Check if it is a digital number
-#%   USAGE: if [ -z $(isdigit 22345876abc) ]; then OR if isdigit 22345876abc 2>/dev/null; then
-#%   REQUIRES: printf
+#   NAME:  isdigit
+#   DESCRIPTION:  Check if it is a digital number
+#   USAGE: if [ -z $(isdigit 22345876abc) ]; then OR if isdigit 22345876abc 2>/dev/null; then
+#   REQUIRES: printf
 #----------------------------------------------------------------------------------------------------------------------
 unset -f isdigit
 isdigit() {
@@ -21,7 +24,6 @@ isdigit() {
         return 1
     fi
 }
-
 
 if [ $# -lt 1 ]; then
     export -f isdigit 2>/dev/null
diff --git a/alpine-base/rootfs/usr/local/bin/isfunction b/alpine-base/rootfs/usr/local/bin/isfunction
--- a/alpine-base/rootfs/usr/local/bin/isfunction
+++ b/alpine-base/rootfs/usr/local/bin/isfunction
@@ -1,11 +1,14 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  isfunction
-#%   DESCRIPTION:  Check if a function is defined
-#%   USAGE: if [ -z $(isfunction psp) ]; then OR if isfunction psp 2>/dev/null; then
-#%   REQUIRES: type, grep
+#   NAME:  isfunction
+#   DESCRIPTION:  Check if a function is defined
+#   USAGE: if [ -z $(isfunction psp) ]; then OR if isfunction psp 2>/dev/null; then
+#   REQUIRES: type, grep
 #----------------------------------------------------------------------------------------------------------------------
 unset -f isfunction
 isfunction() {
diff --git a/alpine-base/rootfs/usr/local/bin/killzb b/alpine-base/rootfs/usr/local/bin/killzb
--- a/alpine-base/rootfs/usr/local/bin/killzb
+++ b/alpine-base/rootfs/usr/local/bin/killzb
@@ -1,11 +1,14 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  killzb
-#%   DESCRIPTION:  Kill all zombie proesses
-#%   USAGE: killzb
-#%   REQUIRES: ps, shc, grep, awk, kill
+#   NAME:  killzb
+#   DESCRIPTION:  Kill all zombie proesses
+#   USAGE: killzb
+#   REQUIRES: ps, shc, grep, awk, kill
 #----------------------------------------------------------------------------------------------------------------------
 _killzb() {
     echo "Plan to kill defunct and zombie processes:"
@@ -31,7 +34,6 @@ _killzb() {
         echo "No zombie processes are found."
     fi
 }
-
 
 _killzb
 
diff --git a/alpine-base/rootfs/usr/local/bin/nrows b/alpine-base/rootfs/usr/local/bin/nrows
--- a/alpine-base/rootfs/usr/local/bin/nrows
+++ b/alpine-base/rootfs/usr/local/bin/nrows
@@ -1,18 +1,21 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  nrows
-#%   DESCRIPTION:  Get the number of rows of the given string
-#%   USAGE: nrows "string paragraph" or psp salt | nrows
-#%   REQUIRES: printf, awk
+#   NAME:  nrows
+#   DESCRIPTION:  Get the number of rows of the given string
+#   USAGE: nrows "string paragraph" or psp salt | nrows
+#   REQUIRES: printf, awk
 #----------------------------------------------------------------------------------------------------------------------
 
 if [ $# -lt 1 ]; then
-        ## sed -n '$=' may has buffer size limit
-        printf "%s" "$(cat)" | awk 'END {print NR;exit}'
+    ## sed -n '$=' may has buffer size limit
+    printf "%s" "$(cat)" | awk 'END {print NR;exit}'
 else
-        printf "%s" "$*" | awk 'END {print NR;exit}'
+    printf "%s" "$*" | awk 'END {print NR;exit}'
 fi
 
 exit 0
diff --git a/alpine-base/rootfs/usr/local/bin/waiton b/alpine-base/rootfs/usr/local/bin/waiton
--- a/alpine-base/rootfs/usr/local/bin/waiton
+++ b/alpine-base/rootfs/usr/local/bin/waiton
@@ -1,11 +1,14 @@
 #!/bin/sh
-    
+
+set -o nounset     # Strict var declare
+set -o errexit     # Exit on error
+
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  waiton
-#%   DESCRIPTION:  Wait until the given pid finish
-#%   USAGE: waiton "$(getpid curl)"
-#%   REQUIRES: ps, sleep, getpnamebyid
+#   NAME:  waiton
+#   DESCRIPTION:  Wait until the given pid finish
+#   USAGE: waiton "$(getpid curl)"
+#   REQUIRES: ps, sleep, getpnamebyid
 #----------------------------------------------------------------------------------------------------------------------
 _waiton() {
    if [ -z "$*" ]; then
diff --git a/alpine-base/rootfs/usr/local/sbin/set-timezone b/alpine-base/rootfs/usr/local/sbin/set-timezone
--- a/alpine-base/rootfs/usr/local/sbin/set-timezone
+++ b/alpine-base/rootfs/usr/local/sbin/set-timezone
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# set -e : Exit the script if any statement returns a non-true return value.
+set -e
+
 readonly PROGNAME=$(basename $0)
 
 if [ $# -ne 1 ]; then
diff --git a/alpine-runit/rootfs/etc/runit/1 b/alpine-runit/rootfs/etc/runit/1
--- a/alpine-runit/rootfs/etc/runit/1
+++ b/alpine-runit/rootfs/etc/runit/1
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # Initialisation tasks
 #
@@ -6,32 +6,41 @@
 # This is the good place to add all you initialisation scripts
 
 # set -e : Exit the script if any statement returns a non-true return value.
-# set -o pipefail : Check the exit code of pipeline's last command.
 # set -u : Exit the script when using uninitialised variable.
+# set -o pipefail : Check the exit code of pipeline's last command.
 set -euo pipefail
 
-echo "-- Starting ..."
+# Add libraries
+source /usr/local/lib/bash-logger.sh
+source /usr/local/lib/persist-env.sh
+
+#
+INFO "[RUNIT] Starting ..."
 
 # Run every scripts in /etc/runit/init.d
 if [ -n "$(ls -A /etc/runit/init.d)" ]; then
-    echo "-- Running initialization scripts ..."
+    #
+    INFO "[RUNIT] Running initialization scripts ..."
     # Iterate throw all script in /etc/runit/init.d/
     # and run them if the scripts are executable
     # and if runit is not stoping
     for _script in /etc/runit/init.d/*; do
         if [ -x "${_script}" ] && [ ! -e /etc/runit/stopall ]; then
-            #echo "-- Running: ${_script}"
+            #
+            DEBUG "[RUNIT] Running ${_script}"
+            #
             ${_script}
             retval=$?
+            #
             if [ ${retval} != 0 ]; then
-                echo >&2 "-- Failed to run ${_script} with return value: ${retval}"
+                ERROR "[RUNIT] Failed to run ${_script} with return value: ${retval}"
                 if [ ${FAIL_MODE} -eq 1 ]; then
                     touch /etc/runit/stopall
                     exit 100
                 fi
             fi
         else
-            echo >&2 "-- Failed to run: ${_script}. Please chmod +x ${_script}"
+            WARNING "[RUNIT] Failed to run: ${_script}. Please chmod +x ${_script}"
         fi
     done
 fi
diff --git a/alpine-runit/rootfs/etc/runit/3 b/alpine-runit/rootfs/etc/runit/3
--- a/alpine-runit/rootfs/etc/runit/3
+++ b/alpine-runit/rootfs/etc/runit/3
@@ -1,52 +1,61 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # set -e : Exit the script if any statement returns a non-true return value.
-# set -o pipefail : Check the exit code of pipeline's last command.
 # set -u : Exit the script when using uninitialised variable.
+# set -o pipefail : Check the exit code of pipeline's last command.
 set -euo pipefail
+
+# Add libraries
+source /usr/local/lib/bash-logger.sh
+source /usr/local/lib/persist-env.sh
 
 # Runlevels 0: Halt
 LAST=0
 # Runlevels 6: Reboot
 test -x /etc/runit/reboot && LAST=6
 
-echo "-- Shutting down"
+#
+INFO "[RUNIT] Shutting down ..."
 
 # Stop every services : http://smarden.org/runit/sv.8.html
 if [ -n "$(ls -A /etc/service)" ]; then
-    echo "-- Waiting for services to stop ..."
+    #
+    INFO "[RUNIT] Waiting for services to stop ..."
 
     # First try to stop services by the reverse order
     for _srv in $(ls -r1 /etc/service); do
+        DEBUG "[RUNIT] Stopping ${_srv} ..."
         sv -w196 force-stop ${_srv} 2>/dev/null
     done
 
-    # Then force stop all service if there any remains
+    # Then force stop all service if any remains
     sv -w196 force-stop /etc/service/* 2>/dev/null
 
-    echo "-- All services are stopped"
+    #
+    INFO "[RUNIT] All services are stopped"
 fi
 
 # Run every scripts in /etc/runit/finish.d
 # before shutting down runit
 if [ -n "$(ls -A /etc/runit/finish.d)" ]; then
-    echo "-- Running shutdown scripts ..."
+    #
+    INFO "[RUNIT] Running shutdown scripts ..."
 
     # Iterate throwall script in /etc/runit/finish.d/
     # and run them if the scripts are executable
     for _script in /etc/runit/finish.d/*; do
         if [ -x ${_script} ]; then
-            echo "-- Running: ${_script}"
+            DEBUG "[RUNIT] Running ${_script}"
             ${_script}
         else
-            echo >&2 "-- Failed to run: ${_script}. Please chmod +x ${_script}"
+            ERROR "[RUNIT] Failed to run: ${_script}. Please chmod +x ${_script}"
         fi
     done
 fi
 
 # Just to make sure that runit will start
 # at next start up
-\rm -f /etc/runit/stopall
+rm -f /etc/runit/stopall
 
 # Change the runlevel
 [ -x /etc/init.d/rc ] && /etc/init.d/rc ${LAST}
diff --git a/alpine-runit/rootfs/usr/local/bin/runit b/alpine-runit/rootfs/usr/local/bin/runit
--- a/alpine-runit/rootfs/usr/local/bin/runit
+++ b/alpine-runit/rootfs/usr/local/bin/runit
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 #
 # This is the runit entrypoint
@@ -7,6 +7,9 @@
 # set -e : Exit the script if any statement returns a non-true return value.
 # set -u : Exit the script when using uninitialised variable.
 set -eu
+
+# Add libraries
+source /usr/local/lib/persist-env.sh
 
 # Default values
 progname=$(basename $0)
@@ -17,7 +20,7 @@ if [ $# -lt 1 ]; then
     echo ""
     echo "$progname : Simple Service Manager for Runit"
     echo ""
-    echo "Type $progname help | to see how to list, start, stop Runit and much more."
+    echo "Run  $progname help | to see how to list, start, stop Runit and much more."
     echo "Or   $progname service help | to see all actions possible for any services."
     echo ""
     exit 0
@@ -29,14 +32,14 @@ _serviceactions="enable disable start stop status reload restart up down once pa
 _servicetpldir="/etc/service.d"
 _servicedir="/etc/service"
 
-function getHelp() {
+getHelp() {
     cat << USAGE >&2
 
 $progname : Simple Service Manager for Runit
 
 Usage: $progname [OPTIONS]
 
-    -h|--help|help              Get  list of installed services
+    -h|--help|help              Get some help
     -l|--ls|--list|ls|list      Get list of installed services
     --start|start               Start Runit
     --stop|stop                 Stop Runit
@@ -47,7 +50,7 @@ USAGE
 }
 
 # Get the list of installed services
-function listServices() {
+listServices() {
     echo "-- List of installed services:"
     if [ -n "$(ls -A ${_servicetpldir})" ]; then
         for _dir in ${_servicetpldir}/*; do
@@ -62,12 +65,12 @@ function listServices() {
 }
 
 # Check if runit is started
-function isStarted() {
+isStarted() {
     [ -n "$(getpidsbyname runsvdir 2>/dev/null)" ] && return 0 || return 1
 }
 
 # Start Runit
-function start() {
+start() {
     # Exit if runit is already started
     isStarted && ( >&2 echo "runit is already started." && return 1 )
     # Run runit init wrapper
@@ -81,7 +84,7 @@ function start() {
 }
 
 # Stop Runit
-function stop() {
+stop() {
     # Exit if runit is not started
     isStarted || ( >&2 echo "Cannot stop runit has it is not started." && return 1 )
     # Get runit-init id
@@ -92,8 +95,8 @@ function stop() {
     waiton $_pid 2>/dev/null
 }
 
-# Dsiplay service help
-function getServiceHelp() {
+# Display service help
+getServiceHelp() {
     echo ""
     echo "$progname : Simple Service Manager for Runit"
     echo ""
@@ -105,27 +108,26 @@ function getServiceHelp() {
 }
 
 # Check if a service exist
-function serviceExist() {
+serviceExist() {
     [ "$#" = 0 ] && return 2
     [ ! -d "${_servicetpldir}/$1" ] && return 1
     return 0
 }
 
 # Check if a service is enable
-function serviceIsEnable() {
+serviceIsEnable() {
     [ "$#" = 0 ] && return 2
     [ ! -d "${_servicedir}/$1" ] && return 1
     return 0
-
 }
 
 # Enable a service
-function serviceEnable() {
+serviceEnable() {
     [ "$#" = 0 ] && return 2
     # the service must exist
     serviceExist $1 || ( >&2 echo "Service \"$1\" doesn't exist." && return 1 )
     # the service must be disable
-    serviceIsEnable $1 && ( >&2 echo "Service \"$1\" already enabled." && return 1 )
+    serviceIsEnable $1 && ( >&2 echo "Service \"$1\" is already enabled." && return 1 )
 
     # Create symbolic link from /etc/service.d to /etc/service
     ln -sf ${_servicetpldir}/$1 ${_servicedir}
@@ -135,12 +137,12 @@ function serviceEnable() {
 }
 
 # Enable a service
-function serviceDisable() {
+serviceDisable() {
     [ "$#" = 0 ] && return 2
     # the service must be enable
     serviceIsEnable $1 || ( >&2 echo "Service \"$1\" is not enabled." && return 1 )
     # Shut down the service
-    sv down ${1} || ( >&2 echo "Unable to to shut down  \"$1\"." && return 1 )
+    sv down $1 || ( >&2 echo "Unable to shut down  \"$1\"." && return 1 )
 
     # Remove the symbolic link
     rm ${_servicedir}/$1
@@ -150,7 +152,7 @@ function serviceDisable() {
 }
 
 # Execute service action
-function serviceAction() {
+serviceAction() {
     sv ${1} ${2}
 }
 
@@ -204,7 +206,7 @@ case "$1" in
             ;;
             - | -- | *)
                 echo "[Error] - $1 is not a supported action."
-                echo "[Error] - Please type $progname for usage details."
+                echo "[Error] - Please run $progname for usage details."
             ;;
             esac
         #
@@ -213,7 +215,7 @@ case "$1" in
             _servicename=$1
             if [ ! -d "${_servicetpldir}/${_servicename}" ] || [ ! -e "${_servicetpldir}/${_servicename}/run" ]; then
                 echo "[Error] - ${_servicename} is not a valid service name."
-                echo "[Error] - Please type $progname list fot the full list of available services."
+                echo "[Error] - Please run $progname list fot the full list of available services."
             else
                 # Check the action
                 _action=$2
@@ -230,13 +232,13 @@ case "$1" in
                         serviceAction ${_action} ${_servicename}
                     else
                         echo "[Error] - ${_action} is not a supported action."
-                        echo "[Error] - Please type $progname for usage details."
+                        echo "[Error] - Please run $progname for usage details."
                     fi
                 fi
             fi
         elif [ $# -gt 2 ]; then
             echo "[Error] - Too many parameters."
-            echo "[Error] - Please type $progname for usage details."
+            echo "[Error] - Please run $progname for usage details."
         fi
     ;;
 
@@ -251,7 +253,7 @@ case "$1" in
 esac
 
 unset getHelp listServices isStarted start stop shutdown
-unset  getServiceHelp serviceExist serviceIsEnable serviceEnable serviceDisable
+unset getServiceHelp serviceExist serviceIsEnable serviceEnable serviceDisable
 unset _runitactions _serviceactions _servicetpldir _servicetdir _dir
 unset _runitinitid _servicename _action
 
